### ISSUE TITLE
Error when running GoalExplore-1.2.0

### ISSUE THREAD

**Issue by XYIheng** [resess/GoalExplorer#10]
Hi, I am running the GoalExplorer-1.2-SNAPSHOT-jar-with-dependencies.jar provided in the github release. However, I encounter an error.

![image](https://github.com/resess/GoalExplorer/assets/31406320/fd30eb18-92b9-4c2f-8797-195d5c35e42a)
![image](https://github.com/resess/GoalExplorer/assets/31406320/95d7e354-c775-44b7-b40e-10129e32c539)
 
Can you help me? 
Thanks a lot

**Comment by dah-fari7009** [comment]
Hi,

Thanks for bringing this to our attention. It seems that the jar under release is not up to date with the latest version of the source code. You can either build the source code or try with the updated jar I just pushed :)

Also, regarding the first picture, please make sure that the decompiled version of the apk is produced under the output folder for Backstage to run properly.

**Comment by XYIheng** [comment]
@dah-fari7009 Thanks for your quickly repsponse! I download the latest jar you just pushed and run it successfully. Great! 
Thanks again for your help~

**Comment by XYIheng** [comment]
@dah-fari7009  Hello, I run the latest jar with "java -jar target/GoalExplorer-1.2-SNAPSHOT-jar-with-dependencies.jar ge -i nl.mpcjanssen.simpletask_11000001.apk -s ~/Android -o ./output/ --target "act:nl.mpcjanssen.simpletask.Preferences" "
And get the ouput
![image](https://github.com/resess/GoalExplorer/assets/31406320/7115d612-2a11-43e7-8b8a-6211c84219fd)

However, I don't know how to analyze the generated output, could you help me?
I want to know how can I get the path to the target (e.g., activity) from the generated output

**Comment by dah-fari7009** [comment]
Hi,

The output represents the graph in XML format, where _``screenNodeSet``,`` serviceNodeSet``_ and _``broadcastReceiverNodeSet``_ contain all the screens (i.e., activities with variations of fragments, menu and dialogs), services and broadcast receivers respectively. Target nodes are marked with _``<target>true</target>``_

_``transitionEdges``_ contains all the edges in the graph, each from a source node (srcNode) to a destination node (tgtNode).

To get the path, from a given screen (e.g., MainActivity) to a target, you can either trace it manually (i.e., find the sequence of edges in _transitionEdges_ starting from MainActivity as a srcNode and leading to the screen you're interested in) or you can write a script to parse the xml. 
There's a number of XML parsers that could help with this task, e.g., [xml.etree](https://docs.python.org/3/library/xml.etree.elementtree.html) or [nokogiri](https://nokogiri.org/) which is used in the dynamic runner, see [GoalExplorer/Stoat/a3e/bin/stg.rb](https://github.com/resess/GoalExplorer/blob/5680bb508de463675c447596bddbe803e507d215/Stoat/a3e/bin/stg.rb#L583) for an example

**Comment by Connor-fire** [comment]
@dah-fari7009 Sorry to bother you. For the tested APK, do we need to manually use apktool or other tools to decompile the apk and put the generated decompiled files into the output folder? Or does GoalExplorer decompile automatically?

**Comment by XYIheng** [comment]
I think that the GoalExplorer would decompile it automatically. @Connor-fire

**Comment by XYIheng** [comment]
@dah-fari7009 Thanks again for your kind response! Your answer solved my question

**Comment by dah-fari7009** [comment]
Of course, happy to help :)
