### ISSUE TITLE
Failed to build STG

### ISSUE THREAD

**Issue by Connor-fire** [resess/GoalExplorer#11]
[test.zip](https://github.com/resess/GoalExplorer/files/11701802/test.zip)
Sorry to bother you. I recently tried to build STG for three apps using GoalExplorer (latest version), but it seems to hit some bugs that prevents it from outputting the app_stg.xml file:

![image](https://github.com/resess/GoalExplorer/assets/55130798/425a8301-a8d9-41a4-aaf1-a979a04492d5)

![image](https://github.com/resess/GoalExplorer/assets/55130798/660507d0-5111-49b0-9c2f-be83145c046f)

![image](https://github.com/resess/GoalExplorer/assets/55130798/01b53d7a-8bf0-4fa7-98a5-056cc2eb6c06)

I have attached the three applications (if needed) that cause the above error. Sorry to bother you. Looking forward to your reply.

**Comment by dah-fari7009** [comment]
Hi @Connor-fire 
Could you please provide the detailed command you used to run the tool on these apps (i.e, which options)?
Also, note that one of these apps targets a SDK version greater than the one supported by the tool (25).

I am a bit busy at the moment, but I will try to look into it as soon as possible. Feel free to make a PR, if you do figure out the issue :)

**Comment by Connor-fire** [comment]
Thanks for your reply. Here's the command I use to run GoalExplorer:
![image](https://github.com/resess/GoalExplorer/assets/55130798/82c2ea54-0b3b-443a-b3cb-2866795c31ee)

![image](https://github.com/resess/GoalExplorer/assets/55130798/1c13c734-269d-4fe8-b2ba-127bf36ab2d8)

![image](https://github.com/resess/GoalExplorer/assets/55130798/4312a5a8-6369-4901-b7ed-03b1458a1d0a)

**Comment by dah-fari7009** [comment]
Hi Connor,

Sorry it look so long to get back to this issue. The latest released jar should address the first two issues in the screenshots. The last one is a bug within FlowDroid itself, which requires rebuilding that dependency as per #12
