### ISSUE TITLE
The APK file is not decompiled during the GoalExplorer.jar execution

### ISSUE THREAD

**Issue by maryammsd** [resess/GoalExplorer#5]
Hello, 

I have been trying your tool recently. I noticed that the decompilation with apktool is not performed. After going through your code, I notice that at line 114 of class Main_UI_Analysis.java, the string used defining apktool is not correct. It seems there is a specific setting for having apktool. Please clarify it in the readme file.

**Comment by dah-fari7009** [comment]
Hi,

The latest commit should fix this problem. Also, note that the tool only expects the decompiled apk to be located under the folder provided with the option --output, so the decompilation step could also be performed separately first with apktool.

**Comment by maryammsd** [comment]
Not at all. I see. Thanks for clarifying it. It would be good if you give an example in the Readme as well. It is a week I am trying your work but still couldn't successfully perform the experiments with Stoat and GoalExplorer.
