### ISSUE TITLE
Question About ICCBot

### ISSUE THREAD

**Issue by maryammsd** [resess/GoalExplorer#7]
Hi again, 

I am working with your tool, when I perform the static analysis with goalexplorer on an application, I get the following error: 

ERROR: IOException when parsing transition file java.io.FileNotFoundException: ./implementation/GoalExplorer/iccbot/AnkiDroid-debug-2.10beta3-#6145-iccbot-output.json (No such file or directory)

So, I am really confused on how to work with your tool and how to resolve this issue. I would be grateful if you can help me

**Comment by dah-fari7009** [comment]
Hi,

You can safely ignore this error as the tool will still produce an STG even without ICCBot data. This is mainly for experimentation purposes.
