### ISSUE TITLE
Exceptions in the static analysis module

### ISSUE THREAD

**Issue by Connor-fire** [resess/GoalExplorer#8]
I successfully built the project and successfully generated GoalExplorer-1.2-SNAPSHOT-jar with dependencies. jar under "target".

However, I encountered a problem executing the following command from the readme file.

Command:
`java -jar target/GoalExplorer-1.2-SNAPSHOT-jar-with-dependencies.jar ge -i /home/xxx/AndroidTools/GoalExplorer-main/ExperimentSubject/org.tomdroid_14.apk --target "act:org.tomdroid.ui.PreferencesActivity" -s /home/xxx/Android/Sdk -o /home/xxx/AndroidTools/GoalExplorer-main/GoalExplorer/sootOutput`

Error reporting information：
![image](https://user-images.githubusercontent.com/55130798/229266692-5defafa6-7482-4756-b606-640eb8fef43d.png)

I would be grateful if you can help me.

**Comment by dah-fari7009** [comment]
Hello,
Thank you for bringing this to our attention! The latest commit should fix this issue.

**Comment by Connor-fire** [comment]
Thanks for your help.
