### ISSUE TITLE
Confusion during using

### ISSUE THREAD

**Issue by Connor-fire** [resess/GoalExplorer#9]
Hello,
Sorry to bother you. Is the "<java." at the mark in the following figure redundant.  If not, can you give an appropriate explanation.
I would be grateful if you can help me.

![image](https://user-images.githubusercontent.com/55130798/229454729-8fa84640-8cff-4e45-b95a-7654c2e5136a.png)

**Comment by dah-fari7009** [comment]
Hi, yes it is redundant. I'll fix it accordingly, thanks for the notice!
